### ISSUE TITLE
Optimiser le create-release.yml pour ne pas générer 3 build

### ISSUE THREAD

**Issue by kerphi** [abes-esr/abes-hello-back#62]
L'idée serait que le workflow create-release.yml (à faire sur abes-hello-back et abes-hello-front) ne génère pas 3 build quand il se produit : 
![image](https://user-images.githubusercontent.com/328244/167395800-75a391e1-1bfc-4594-87f7-8c673e8224ba.png)

En effet actuellement nous avons ce comportement :
- un commit sur main (troisième ligne) qui consiste justement à modifier les numéros de version du pom.xml ou package.json
- un tag sur main (2eme ligne) qui consiste à tagguer la version
- un commit sur develop (première ligne) qui est la conséquence du rapatriement des modifs de numéro de version sur develop

Les lignes 1 et 3 sont des build/déploiement potentiellement inutiles car c'est juste des numéros de version qu'on modifie.
Le top serait de ne conserver que le workflow de la ligne 2 ce qui économise des build et des déploiements inutiles sur les serveurs.

Cf la piste https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs

cc @natman

**Comment by natman** [comment]
Il y a 3 builds qui correspondent à 3 push dans le create-release.yml:

1. ajout de packages.json, packages-lock.json et README.md dans la branche main
2. merge de la branche main dans develop
3. création du tag

Chacun de ces builds entraine un trigger webhook qui déclenche lui-même un workflow AWX/ansible inutile.
Suivant [](https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs), il est possible d'éviter le déclenchement des workflows avec l'ajout de mention de type '[no ci]' dans le commentaire du commit.
C'est ce qui est fait dans  les 2 premiers cas. 
Concernant le 3ème, c'est plus délicat puisque pusher des tags s'appuie sur les commentaires du dernier commit qui contient la mention '[no ci]'. Il faut donc un nouveau commit qui n'ait pas cette mention pour que le push déclenche le build sur le tag voulu.
On crée pour cela un fichier fantôme qui va justifier un nouveau commit sans push.

**Comment by natman** [comment]
Par contre, il n'est pas possible d'envisager le même principe sur la partie back puisque c'est maven qui gère l'ajout de tag et donc la création de la release lui-même. 
![image](https://user-images.githubusercontent.com/1138093/167805389-5a6b620d-e593-483f-a63a-01947c59d7cd.png)
ce qui nous conduit même à 4 builds:
![image](https://user-images.githubusercontent.com/1138093/167805718-9f587d9f-7a0f-4746-8978-65396a5e9654.png)
On peut uniquement restreindre le dernier build concernant le merge par le '[no ci]'.
Peut-on envisager de dire à maven de commenter les builds de main avec '[no ci]' pour restreindre les builds au tag comme dans la partie front?
